### PR TITLE
Migrate to xorg-xorgproto

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
I wonder if we can get this transition complete by just adding a little linter rule

```
        - xorg-xextproto
        - xorg-glproto
        - xorg-xorgproto
```

you can add the old protos to
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/linter_hints/hints.toml

**Comment by ehfd** [comment]
@hmaarrfk I think so, but the old protos aren't archived yet. When some kind of conda-forge wide migration for this happens.

**Comment by hmaarrfk** [comment]
you can launch it, but what is the real harm? a ~conflict~ clobber of header files. that is pretty minor IMO.


edit: conflict -> clobber

**Comment by ehfd** [comment]
Anyways, it's a bit early because I'm not sure all of the X11 packages are done migrating.

**Comment by hmaarrfk** [comment]
> Anyways, it's a bit early because I'm not sure all of the X11 packages are done migrating.

why i thought `xorg-xorgproto` was a superset of all packages.

just remind people (yourself, myself, and pkwg) to depend on that.

**Comment by ehfd** [comment]
> why i thought xorg-xorgproto was a superset of all packages.

I am just cautious because this can lead to failures downstream. I had an experience where colliding headers that were installed together through distinct dependencies failed conda-build.

**Comment by ehfd** [comment]
I will reference @pkgw for the final decision on this.

**Comment by ehfd** [comment]
@hmaarrfk

> I wonder if we can get this transition complete by just adding a little linter rule

Can this be done as a regex `xorg-[^(?!xorg$)]proto`? Don't really know how many legacy proto packages exist.

**Comment by pkgw** [comment]
I believe there are about 33 legacy proto packages, based on:

<https://www.x.org/releases/individual/proto/>

Everything **except** `xcb-proto` is all merged into `xorg-xorgproto` now. It's also worth mentioning that the old proto packages are no longer getting updated, so this migration is necessary. There was a case where a library wouldn't build (I think it was `libxinput`) because it needed newer prototypes that were provided in the `xorgproto` version of the input prototypes, but not in the `inputproto` version.

Another factor: before, because there were so many `proto` packages I added them as `run` dependencies of the `xorg-libx*` library packages, since it would be a big pain to have to remember "OK, since I'm building against `xorg-libxaw3d`, I need to also depend on `xorg-inputproto`, `xorg-xproto`, `xorg-fixproto`, ....".

Now that there's basically only one package, I got rid of those `run` dependencies. So, packages that have host deps on `xorg-libx*` libraries will probably need to add a host dep on `xorg-xorgproto` as well. This is another thing that it would be nice to have a linter/migration check for.

**Comment by pkgw** [comment]
Oh, and, at this point I believe that the core `xorg-*` packages are all done migrating to the new UCRT Windows runtime + `xorgproto` standard. I haven't checked the migration status for a while but I've stopped seeing PRs to those packages, and I did a pass over the migration status a couple of weeks ago and there weren't any `xorg-*` packages left in the queue.

**Comment by ehfd** [comment]
I compiled relevant information to https://github.com/conda-forge/staged-recipes/issues/26241 @pkgw

**Comment by ehfd** [comment]
@isuruf @hmaarrfk 

https://conda-forge.org/docs/maintainer/maintainer_faq/#how-do-i-fix-the-libglso1-import-error
I think this needs to be fixed so that it points to `host: libgl-devel` and add https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/linter_hints/hints.toml.

**Comment by h-vetinari** [comment]
> I think this needs to be fixed so that it points to `host: libgl-devel`

Could you please open a PR to https://github.com/conda-forge/conda-forge.github.io?

**Comment by ehfd** [comment]
Opened in https://github.com/conda-forge/conda-forge.github.io/pull/2334 but the linter hints for the relevant Mesa/OpenGL CDTs should also be added.

**Pull request merged**
