### PR TITLE
Allow usage of `${CONDA_PREFIX}/etc/glvnd/egl_vendor.d`

### LINKED ISSUE #3: Allow usage of `${CONDA_PREFIX}/etc/glvnd/egl_vendor.d`
### Comment:

CC @hmaarrfk @traversaro @isuruf 

https://github.com/conda-forge/ocl-icd-feedstock and https://github.com/conda-forge/ocl-icd-system-feedstock allow using a prefix path for OpenCL's ICD files.

It seems that when a path including `${PREFIX}` is used for https://github.com/conda-forge/ocl-icd-feedstock/blob/main/recipe/build.sh, Conda's compiler somehow translates it into `${CONDA_PREFIX}`.
However, I am unsure of the mechanism by which this works and how it will be applicable for Meson (https://github.com/conda-forge/libglvnd-feedstock/blob/main/recipe/libglvnd_look_for_egl_icd_in_system_location.patch) instead of autoconf.

If possible, https://github.com/conda-forge/ocl-icd-feedstock/blob/main/recipe/check_icds_recursively.diff should not be necessary because multiple directories can be specified in https://github.com/conda-forge/libglvnd-feedstock/blob/main/recipe/libglvnd_look_for_egl_icd_in_system_location.patch.

Anyone who can properly explain how this would work and/or contribute a patch would be extremely thankful.

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #3

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@traversaro Possible to check whether the binary prefix patch is done correctly?

**Comment by ehfd** [comment]
CC @isuruf @hmaarrfk for review

**Comment by traversaro** [comment]
> @traversaro Possible to check whether the binary prefix patch is done correctly?

Some thing is happening, see the log:

~~~
2024-11-11T11:31:59.8119724Z lib/libEGL.so.1.1.0 (binary): Patching
~~~

To see if it actually works, I am afraid you need to manually test the package.

**Comment by ehfd** [comment]
I will test the package. Just needed to understand the patch works. Thanks.

**Comment by ehfd** [comment]
Tried to remove system paths and added local paths. Works with relatively high confidence.

**Pull request merged**
